# Generated by Django 4.2 on 2023-05-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='worker',
            name='adress',
            field=models.CharField(blank=True, max_length=50, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Фото сотрудника'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
    ]
