# Generated by Django 4.2 on 2023-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_options_alter_worker_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='telephone',
            field=models.CharField(max_length=12),
        ),
    ]
