# Generated by Django 4.2 on 2023-05-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_worker_options_alter_worker_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='telephone',
            field=models.CharField(max_length=14, verbose_name='Телефон'),
        ),
    ]
