# Generated by Django 4.2 on 2023-05-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_alter_worker_is_monthworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='is_monthworker',
            field=models.BooleanField(default=False, verbose_name='Сотрудник месяца'),
        ),
    ]
