# Generated by Django 4.2 on 2023-05-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_alter_worker_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='is_monthworker',
        ),
    ]
