# Generated by Django 4.2 on 2023-05-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_remove_worker_is_monthworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='adress',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
    ]
